// <auto-generated />
using ComplexUnitOfWork.UnitOfWork.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComplexUnitOfWork.Migrations
{
    [DbContext(typeof(SampleContext))]
    partial class SampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComplexUnitOfWork.Model.Locale", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.ToTable("Locales");

                    b.HasData(
                        new
                        {
                            Id = "en-GB"
                        },
                        new
                        {
                            Id = "hu-HU"
                        });
                });

            modelBuilder.Entity("ComplexUnitOfWork.Model.Sample", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("LocaleId")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocaleId");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("ComplexUnitOfWork.Model.Sample", b =>
                {
                    b.HasOne("ComplexUnitOfWork.Model.Locale", "Locale")
                        .WithMany()
                        .HasForeignKey("LocaleId");
                });
#pragma warning restore 612, 618
        }
    }
}
